-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 19:17:25 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basedeDatos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basedeDatos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basedeDatos` DEFAULT CHARACTER SET utf8 ;
USE `basedeDatos` ;

-- -----------------------------------------------------
-- Table `basedeDatos`.`register`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedeDatos`.`register` (
  `Nombre` VARCHAR(100) NOT NULL,
  `Apellido` VARCHAR(100) NOT NULL,
  `Id` INT NOT NULL AUTO_INCREMENT,
  `Email` VARCHAR(100) NOT NULL,
  `Usuario` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Id`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `basedeDatos`.`logins` (`Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basedeDatos`.`logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedeDatos`.`logins` (
  `Idusuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(100) NOT NULL,
  `Contraseña` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`Idusuario`),
  INDEX () VISIBLE,
  INDEX `Usuario_idx` (`Usuario` ASC) VISIBLE,
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC) VISIBLE,
  CONSTRAINT `Usuario`
    FOREIGN KEY (`Usuario`)
    REFERENCES `basedeDatos`.`register` (`Usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basedeDatos`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basedeDatos`.`products` (
  `idProducto` INT NOT NULL,
  `Categoria` VARCHAR(100) NOT NULL,
  `Marca` VARCHAR(100) NOT NULL,
  `Descripcion` VARCHAR(100) NOT NULL,
  `Cantidad` INT NOT NULL,
  `Precio` DECIMAL(2) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `basedeDatos`.`register`
-- -----------------------------------------------------
START TRANSACTION;
USE `basedeDatos`;
INSERT INTO `basedeDatos`.`register` (`Nombre`, `Apellido`, `Id`, `Email`, `Usuario`, `Contraseña`) VALUES ('lucas', 'perez', 1, 'lucas3_@gmail.com', 'lucas', 'lucas2356');
INSERT INTO `basedeDatos`.`register` (`Nombre`, `Apellido`, `Id`, `Email`, `Usuario`, `Contraseña`) VALUES ('luisa', 'mora', 2, 'moralu@hotmail.com', 'luisa', 'luisa34.1');

COMMIT;


-- -----------------------------------------------------
-- Data for table `basedeDatos`.`logins`
-- -----------------------------------------------------
START TRANSACTION;
USE `basedeDatos`;
INSERT INTO `basedeDatos`.`logins` (`Idusuario`, `Usuario`, `Contraseña`) VALUES (1, '', '');
INSERT INTO `basedeDatos`.`logins` (`Idusuario`, `Usuario`, `Contraseña`) VALUES (, '', '');

COMMIT;

